language: php

php:
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - travis_retry composer require --no-update "phpspec/phpspec:~3.0"
  - travis_retry composer require --no-update "laravel/framework:${LARAVEL_VERSION}"

install:
  - composer update

script:
  - ./bin/phpspec run
